name: Website Check

on:
  schedule:
    # This will run at 9 AM UTC every day
    - cron: '0 8 * * *' 
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Website Status
        run: |
          URL="https://www.minidemo.skilledems.com/login" "https://www.demo.skilledems.com/login" "https://www.urielcare.skilledems.com/login" "https://www.ritchies.skilledems.com/login" "https://www.mithaighar.skilledems.com/login" "https://www.devoted.skilledems.com/login" "https://www.graduateplace.skilledems.com/login" "https://www.tandoori.skilledems.com/login" "https://www.keypoint.skilledems.com/login" "https://www.ecogreen.skilledems.com/login" "https://www.nextmove.skilledems.com/login" "https://www.altamira.skilledems.com/login" "https://www.beverage.skilledems.com/login" "https://www.tko.skilledems.com/login" "https://www.elc.skilledems.com/login" "https://www.better.skilledems.com/login" "https://www.servicehub.skilledems.com/login" "https://www.mmholdings.skilledems.com/login"
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" $URL)
          if [ "$STATUS" -eq 200 ]; then
            echo "The website $URL is UP." | tee report.txt
          else
            echo "The website $URL is DOWN. HTTP Status: $STATUS" | tee report.txt
          fi
          # Send email
          echo "Subject: Website Status Report" > email.txt
          cat report.txt >> email.txt
          curl --url 'smtps://smtp.gmail.com:465' --ssl-reqd \
            --mail-from 'mnru194@gmail.com' \
            --mail-rcpt 'mnru117@gmail.com' \
            --upload-file email.txt \
            --user 'mnru194@gmail.com:nztu yuqt kbbw wetp'


