name: Website Status Check

on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 8:00 AM UTC

jobs:
  check-websites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Websites
        run: |
          declare -a WEBSITES=(
            "https://www.minidemo.skilledems.com/login"
          )
          REPORT="Website Status Report - $(date)\n\n"
          for URL in "${WEBSITES[@]}"; do
            STATUS=$(curl -o /dev/null -s -w "%{http_code}" $URL)
            if [ "$STATUS" -eq 200 ]; then
              REPORT+="$URL is UP.\n"
            else
              REPORT+="$URL is DOWN. HTTP Status: $STATUS\n"
            fi
          done
          echo -e "$REPORT" | tee report.txt

          # Send email (example with sendmail)
          echo -e "Subject: Website Status Report\n\n$REPORT" | sendmail -v mnru194@gmail.com
